<php?
print '<HTML>'
print '	<HEAD>'
print '		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">'
print '		<TITLE>ТАРАНИН</TITLE>'
print '		<meta name="Author" content="169">'
print '		<meta name="date" content="09:10:2023">'
print '	</HEAD>'
print '	<BODY>'
print '		<p> с неупорядоченной информацией</p>'
print '		<ul>'
print '			<li>1'
print '			<li style="list-style-type: circle">2'
print '			<li style="list-style-type: square">3'
print '			<li style="list-style-type: circle">4'
print '			<li>5'
print '		</ul>'
print '		<p> с упорядоченной информацией</p>'
print '		<ol>'
print '			<li>6'
print '			<li>7'
print '			<li>8'
print '			<li>9'
print '			<li>10'
print '		</ol>'
print '		<dl>'
print '			<dt> определения/Definitions'
print '			<dd>11'
print '			<dd>12'
print '			<dd>13'
print '			<dd>14'
print '			<dd>15'
print '		</dl>'
print '		<p style="text-align:center"><img src="1.png" alt="1" width="100" height="100"></p>'
print '		<p dir="rtl"><img src="6.png" alt="6" width="25" height="25"></p>'
print '		<p><img src="9.png" alt="9" width="50" height="50"></p>'
print '		<h1 style="text-align:center">История музыки</h1>'
print '		<p dir="rtl">Основная статья: Музыка Древней Греции</p>'
print '		<p>Музыка Древней Греции</p>'
print '		<p>'
print '			<span style="font-size:110%">'
print '				<i>'
print '					<span style="color:red;font-family:Arial;">Веб-дизайн </span>'
print '					<span style="color:#ffba63;">(от англ. Web design)</span>'
print '					<span style="color:#ff9563;"> — отрасль </span>'
print '					<span style="color:#ffe963;"> веб-разработки</span>'
print '					<span style="color:#d0ff63;"> и разновидность </span>'
print '					<span style="color:#a1ff63;">дизайна, </span>'
print '					<span style="color:#6cff63;">в задачи </span>'
print '					<span style="color:#63ffa8;">которой </span>'
print '					<span style="color:#63ffdd;">входит </span>'
print '					<span style="color:#63efff;">проектирование </span>'
print '					<span style="color:#63b4ff;">пользовательских  </span>'
print '					<span style="color:#6385ff;">веб-интерфейсов </span>'
print '					<span style="color:#7663ff;">для </span>'
print '					<span style="color:#b163ff;">сайтов </span>'
print '					<span style="color:#e963ff;">или </span>'
print '					<span style="color:#ff63ec;">веб-приложений.</span>'
print '				</i>'
print '			</span>'
print '		</p>'
print '		<p></p>'
print '		<form action="@">'
print '			<fieldset style="width:700px">'
print '				<legend>Форма регистрации</legend>'
print '				<table border="0">'
print '					<tbody><tr>'
print '						<td>Имя</td>'
print '						<td align="right"><input type="text" id="name" value="" size="30"></td>'
print '						<td rowspan="5"><div style="text-align:center">Пожелания</div><textarea id="comm" cols="40" rows="7"></textarea></td>'
print '					</tr>'
print '					<tr>'
print '						<td>Адрес эл. почты</td>'
print '						<td align="right"><input type="text" id="mail" value="" size="30"></td>'
print '					</tr>'
print '					<tr>'
print '						<td>Пароль</td>'
print '						<td align="right"><input type="text" value="" size="30"></td>'
print '					</tr>'
print '					<tr>'
print '						<td>Пол</td>'
print '						<td><input type="radio" name="пол" value="Мужской">Мужской<input type="radio" name="пол" value="Женский">Женский</td>'
print '					</tr>'
print '					<tr>'
print '						<td>Увлечения</td>'
print '						<td>'
print '							<select id="co">'
print '								<option value="Компьютеры">Компьютеры</option>'
print '								<option value="спорт">спорт</option>'
print '								<option value="игры">игры</option>'
print '								<option value="животные">животные</option>'
print '								<option value="автомобили">автомобили</option>'
print '								<option value="клубы">клубы</option>'
print '								<option value="музыка">музыка</option>'
print '							</select>'
print '						</td>'
print '					</tr>'
print '					<tr>'
print '						<td></td>'
print '						<td align="right"><button type="submit" name="OK" value="OK">Отправить</button></td>'
print '						<td><button type="reset" name="OK" value="неок">Отмена</button></td>'
print '					</tr>'
print '				</tbody></table>'
print '			</fieldset>'
print '		</form>'
print '		<p></p>'
print '		<table border="1" rules="all" width="100%">'
print '		    <caption>Таблица размеров обуви</caption>'
print '		    <tbody><tr>'
print '				<th>Россия</th>'
print '				<th>Великобритания</th>'
print '				<th>Европа</th>'
print '				<th><p>Длина ступни, см Длина ступни, см Длина ступни, см Длина ступни, см Длина ступни, см</p></th>'
print '		    </tr>'
print '		    <tr><td>34,5</td><td>3,5</td><td>36</td><td>23</td></tr>'
print '		    <tr><td>35,5</td><td>4</td><td>36⅔</td><td>23–23,5</td></tr>'
print '		    <tr><td>36</td><td>4,5</td><td>37⅓</td><td>23,5</td></tr>'
print '		    <tr><td>36,5</td><td>5</td><td>38</td><td>24</td></tr>'
print '		</tbody></table>'
print '	</body>'
print '</html>'
